services:
  snapremote:
    container_name: snapremote
    build: .
    devices:
      # Make sure this matches the `WEBCAM_PATH` in the `environment` section.
      # See README.md for more information on determining the correct device path.
      - /dev/video0
    environment:
      # You MUST override values in `[SQUARE BRACKETS]`.
      # You MAY override other values too, of course.
      # See README.md for more information, especially for `JWT_SECRET_KEY`.
      # Override using `docker-compose.override.yaml` or command line arguments.
      - JWT_SECRET_KEY=[YOUR_JWT_SECRET]
      - DEVICE_IP=[SNAPMAKER_DEVICE_IP]
      - DEVICE_PORT=8888
      # These values should only affect activity inside the container
      - PORT=3000
      - WEBCAM_PATH=/dev/video0
    ports:
      # Format: `"host_port:container_port"`
      # Make sure `container_port` matches `PORT` in the `environment` section.
      # Set `host_port` to any available port on your host.
      # Access the web interface at http://{host_ip}:{host_port}/
      # You can override this, too, using `docker-compose.override.yaml` or command line arguments.
      - "8088:3000"
